In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [5]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [9]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [12]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [19]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [20]:
x_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [21]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [22]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [24]:
from keras.models import Sequential
from keras.layers import Dense

In [25]:
ann=Sequential()
ann.add(Dense(units=6,activation="relu"))
ann.add(Dense(units=6,activation="relu"))
ann.add(Dense(units=1,activation="sigmoid"))

In [26]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=["accuracy"])

In [27]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6855 - accuracy: 0.6085
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5284 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4798 - accuracy: 0.7997
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4534 - accuracy: 0.8061
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4357 - accuracy: 0.8101
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4245 - accuracy: 0.8165
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4149 - accuracy: 0.8202
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4029 - accuracy: 0.8255
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3881 - accuracy: 0.8382
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3754 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8641
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8640
Epoch 83/100
250/250 [==============================] - 0s 979us/step - loss: 0.3305 - accuracy: 0.8643
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8626
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8644
Epoch 86/100
250/250 [==============================] - 0s 980us/step - loss: 0.3305 - accuracy: 0.8645
Epoch 87/100
250/250 [==============================] - 0s 999us/step - loss: 0.3305 - accuracy: 0.8651
Epoch 88/100
250/250 [==============================] - 0s 989us/step - loss: 0.3302 - accuracy: 0.8641
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8636
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3306 - ac

In [28]:
ann.save("customer_churn.h5")

 
## Geography:France
## credit score: 600
## gender: male
## age: 40
## tenure: 3
## balance: 60000
## number of products: 2
## credit card: yes
## active member: yes
## estimated salary: 50000
## goodbuy or not? 

In [30]:
ann.predict(scaler.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

array([[0.04194415]], dtype=float32)

In [32]:
ann.predict(scaler.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

array([[False]])

In [35]:
y_pred=ann.predict(x_test)
y_pred=(y_pred)>0.5
predictions=np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

In [36]:
predictions

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [37]:
prediction = pd.DataFrame(predictions, columns=['original','predictions']).to_csv('prediction.csv')

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [42]:
c=confusion_matrix(y_test,y_pred)
print(c)
print("#################")
print("#################")
print("#################")
accu=accuracy_score(y_test,y_pred)
print(accu)

[[1514   81]
 [ 198  207]]
#################
#################
#################
0.8605
